### ISSUE TITLE
Little improvements for usability =)

### ISSUE THREAD

**Issue by astronomyk** [AstarVienna/speXtra#1]
It might make it a bit easier to use if you add to the ``SpecDatabase`` class:

    def __repr__(self):
        return self.as_table()

This will allow the user to type just ``sdb`` to get the table

Another nice little method might be:

    def __getattr__(self, item):
         return self.as_table(item)

This allows the user to type ``sdb["sne"]`` to get the info on the ``sne`` library

**Comment by astronomyk** [comment]
Examples of __getattr__ from Pyckles for accessing self.data["xxx"] is amore efficient way

  
 
 
 https://github.com/astronomyk/Pyckles/blob/485e2ee54980fc048a26a0e7b6a0adb85eb4f8aa/pyckles/spectral_library.py#L108

**Comment by astronomyk** [comment]
Basically you just need something like this:

    def __getattr__(self, item):
        """Looks for item in the self.data dictionary"""
        if item in self.data:
            return self.data["item"]
        else:
            raise ValueError("{} not found in self.data".format(item))

**Comment by teutoburg** [comment]
This was basically done in #10, although in a slightly different way.
